# Generated by Django 2.2.5 on 2019-11-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPolling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date',
            new_name='pub_date',
        ),
    ]
