# Generated by Django 2.2.5 on 2019-11-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPolling', '0002_auto_20191119_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
