# Generated by Django 2.2.5 on 2019-11-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startPolling', '0002_auto_20191114_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='allow_multiple',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='question',
            name='starts_at',
        ),
    ]
