# Generated by Django 2.2.5 on 2019-11-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startPolling', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QuestionText',
            field=models.CharField(error_messages={'QuestionText': 'Hello'}, max_length=500),
        ),
    ]
