# Generated by Django 2.2.5 on 2019-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startPolling', '0005_auto_20191120_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QuestionText',
            field=models.CharField(max_length=500),
        ),
    ]
